##Load

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
!pip install fastparquet

     |████████████████████████████████| 153kB 4.9MB/s 
     |████████████████████████████████| 61kB 9.1MB/s 
  Created wheel for fastparquet: filename=fastparquet-0.4.0-cp36-cp36m-linux_x86_64.whl size=251893 sha256=a3c299ae3f671115c6c9eba067003d0c7fe54c29301775f28898cb85702b2d39
  Stored in directory: /root/.cache/pip/wheels/2f/1d/6f/d10f8d2688469c279b71799a457a1fd8f35e5ba06e91b7d993
  Created wheel for thrift: filename=thrift-0.13.0-cp36-cp36m-linux_x86_64.whl size=345240 sha256=a39a25d9d95d1f5d49828e84f37d7fe4677c3d1aa9f5cbfe041874daef29bfb3
  Stored in directory: /root/.cache/pip/wheels/02/a2/46/689ccfcf40155c23edc7cdbd9de488611c8fdf49ff34b1706e
Successfully built fastparquet thrift


In [ ]:
import numpy as np
import pandas as pd
from fastparquet import ParquetFile
pf = ParquetFile("drive/My Drive/dataset/iot_dataset_2_percent_decom.parquet")
df = pf.to_pandas()

##Check

####Count + category + dtypes

In [ ]:
df.count()

frame.time_epoch              11252406
frame.len                     11252406
ip.proto                      11240346
ip.src                        11240346
ip.dst                        11240346
ip.ttl                        11240346
ipv6.src                            41
ipv6.dst                            41
ip.hdr_len                    11240346
ip.len                        11240346
ip.id                         11240346
ip.flags.df                   11240346
tcp.srcport                    6979907
tcp.dstport                    6979907
tcp.stream                     6979907
tcp.analysis.initial_rtt       1260503
tcp.time_delta                 6979907
tcp.len                        6979907
tcp.flags                      6979907
tcp.window_size_value          6979907
tcp.hdr_len                    6979907
tcp.time_relative              6979907
udp.srcport                    4256583
udp.dstport                    4256583
udp.length                     4256583
udp.stream               

In [ ]:
df[['category', 'subcategory']].groupby(['category', 'subcategory']).size()

category  subcategory      
DDoS      DDoS_HTTP             194417
          DDoS_UDP             1000055
          TCP                   999444
DoS       DoS_HTTP              287480
          DoS_TCP               998703
          DoS_UDP               999977
Normal    Normal               4631398
Scan      OS                    827940
          Service               999895
Theft     Data_Exfiltration     301710
          Keylogging             11387
dtype: int64

In [ ]:
df.dtypes

frame.time_epoch              float64
frame.len                       int32
ip.proto                       object
ip.src                         object
ip.dst                         object
ip.ttl                         object
ipv6.src                       object
ipv6.dst                       object
ip.hdr_len                     object
ip.len                         object
ip.id                          object
ip.flags.df                    object
tcp.srcport                   float64
tcp.dstport                   float64
tcp.stream                    float64
tcp.analysis.initial_rtt       object
tcp.time_delta                float64
tcp.len                       float64
tcp.flags                      object
tcp.window_size_value         float64
tcp.hdr_len                   float64
tcp.time_relative             float64
udp.srcport                   float64
udp.dstport                   float64
udp.length                    float64
udp.stream                    float64
http.respons

####Frame

In [ ]:
df['frame.len'].unique()

array([ 505,  640, 1436, ..., 1048, 1091, 1092], dtype=int32)

####IPv6

In [ ]:
#Count IPv6 packets
df[~df['ipv6.src'].isna()].count()
#dfparq[~dfparq['ipv6.src'].isna()].head(45)

frame.time_epoch              41
frame.len                     41
ip.proto                       0
ip.src                         0
ip.dst                         0
ip.ttl                         0
ipv6.src                      41
ipv6.dst                      41
ip.hdr_len                     0
ip.len                         0
ip.id                          0
ip.flags.df                    0
tcp.srcport                    0
tcp.dstport                    0
tcp.stream                     0
tcp.analysis.initial_rtt       0
tcp.time_delta                 0
tcp.len                        0
tcp.flags                      0
tcp.window_size_value          0
tcp.hdr_len                    0
tcp.time_relative              0
udp.srcport                   24
udp.dstport                   24
udp.length                    24
udp.stream                    24
http.response.code             0
http.content_length_header     0
http.content_length            0
http.request.method            0
attack    

####IP related

In [ ]:
# TCP: 6, UDP: 17, ICMP: 1, IGMP: 2, ESP:50
df['ip.proto'].unique() # Categorical

array([ 6., 17., nan,  1.,  4.,  3.,  2.])

In [ ]:
df['ip.flags.df'].unique() # Categorical

array([ 0.,  1., nan,  2.,  3.])

In [ ]:
df['ip.ttl'].unique()

array(['127.0', '241.0', '64.0', '128.0', None, '50.0', '44.0', '228.0',
       '53.0', '127', '241', '64', '114.0', '46.0', '45.0', '52.0', '52',
       '53', '255', '57', '45', '56', '38', '50', '46', '39', '43', '41',
       '51', '47', '59', '58', '44', '54', '40', '49', '48', '55', '42',
       '37', '64,59', '60', '64,60', '64,255', '64,54', '64,55', '128',
       '128,255', '61', '64,61', '64,56', '64,57', '64,51', '43.0', '229',
       '62', '63', '64,63', '64,64', '128,57', '128,51', '64,62',
       '128,58', '128,62', '238.0', '238', '64,58', '128,59', '64,53',
       '128,64', '128,60', '64,52', '128,61', '128,56', '229.0', '51.0',
       '255.0', '39.0', '64,47', '64,48', '64,41', '64,44', '55.0',
       '57.0', '37.0', '38.0', '47.0', '59.0', '41.0', '58.0', '40.0',
       '49.0', '54.0', '48.0', '56.0', '42.0', '1.0', '64,45', '64,43',
       '64,38', '64,49', '64,40', '64,46', '64,50', '64,39', '64,37',
       '64,42', '1', '128,45', '128,41', '128,37', '128,44', '128,48

In [ ]:
df['ip.hdr_len'].unique()

array(['20.0', None, '20', '20,20', '24.0', '24'], dtype=object)

In [ ]:
df['ip.id'].unique()

array(['0x000004d2', '0x0000c9d2', '0x00006d94', ...,
       '0x000038fc,0x000018a5', '0x00003900,0x00001815',
       '0x0000a9b5,0x00000000'], dtype=object)

In [ ]:
df['ip.id'].str.contains(",").any()

True

In [ ]:
df['ip.len'].unique()

array(['491.0', '626.0', '1422.0', ..., '1034.0', '1077.0', '1078.0'],
      dtype=object)

In [ ]:
df['ip.len'].str.contains(",").any()

True

In [ ]:
# Check non TCP/UDP protocols
df[(df['tcp.srcport'].isna()) & (df['udp.srcport'].isna())]["ip.proto"].unique()

array([None, '1', '1,50', '17.0', '2.0', '2'], dtype=object)

In [ ]:
df[~df['udp.srcport'].isna()].count() + df[~df['tcp.srcport'].isna()].count() + df[(df['tcp.srcport'].isna()) & (df['udp.srcport'].isna())].count() 

frame.time_epoch              11252406
frame.len                     11252406
ip.proto                      11240346
ip.src                        11240346
ip.dst                        11240346
ip.ttl                        11240346
ipv6.src                            41
ipv6.dst                            41
ip.hdr_len                    11240346
ip.len                        11240346
ip.id                         11240346
ip.flags.df                   11240346
tcp.srcport                    6979907
tcp.dstport                    6979907
tcp.stream                     6979907
tcp.analysis.initial_rtt       1260503
tcp.time_delta                 6979907
tcp.len                        6979907
tcp.flags                      6979907
tcp.window_size_value          6979907
tcp.hdr_len                    6979907
tcp.time_relative              6979907
udp.srcport                    4256583
udp.dstport                    4256583
udp.length                     4256583
udp.stream               

In [ ]:
# ip.proto = 2: IGMP
df[(df['tcp.srcport'].isna() & df['udp.stream'].isna() & ~df['ip.proto'].isna())][(df['ip.proto'] == '2') | (df['ip.proto'] == '2.0')]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  


frame.time_epoch  frame.len ip.proto  ... attack category subcategory
11153791      1.529381e+09         60      2.0  ...      0   Normal      Normal
11174904      1.529381e+09         60      2.0  ...      0   Normal      Normal
11183086      1.529381e+09         60        2  ...      0   Normal      Normal
11249352      1.529382e+09         60      2.0  ...      0   Normal      Normal

[4 rows x 33 columns]

In [ ]:
# ip.proto = 1,50: ICMP + ESP
df[(df['tcp.srcport'].isna() & df['udp.stream'].isna() & ~df['ip.proto'].isna())][df['ip.proto'] == '1,50']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  


frame.time_epoch  frame.len ip.proto  ... attack category subcategory
3808393      1.526352e+09         62     1,50  ...      0   Normal      Normal
3808499      1.526352e+09         62     1,50  ...      0   Normal      Normal
3834065      1.526353e+09         62     1,50  ...      0   Normal      Normal
3834208      1.526353e+09         62     1,50  ...      0   Normal      Normal
3834251      1.526353e+09         62     1,50  ...      0   Normal      Normal
3834539      1.526353e+09         62     1,50  ...      0   Normal      Normal

[6 rows x 33 columns]

In [ ]:
# ip.proto = 1: ICMP
df[(df['tcp.srcport'].isna() & df['udp.stream'].isna() & ~df['ip.proto'].isna())][df['ip.proto'] == '1'].count()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until


frame.time_epoch              3868
frame.len                     3868
ip.proto                      3868
ip.src                        3868
ip.dst                        3868
ip.ttl                        3868
ipv6.src                         0
ipv6.dst                         0
ip.hdr_len                    3868
ip.len                        3868
ip.id                         3868
ip.flags.df                   3868
tcp.srcport                      0
tcp.dstport                      0
tcp.stream                       0
tcp.analysis.initial_rtt         0
tcp.time_delta                   0
tcp.len                          0
tcp.flags                        0
tcp.window_size_value            0
tcp.hdr_len                      0
tcp.time_relative                0
udp.srcport                      0
udp.dstport                      0
udp.length                       0
udp.stream                       0
http.response.code               0
http.content_length_header       0
http.content_length 

####TCP related

In [ ]:
df['tcp.flags'].unique() # Categorical

array(['0x00000000', None, '0x00000010', '0x00000018', '0x00000002',
       '0x00000012', '0x00000011', '0x00000014', '0x00000004',
       '0x00000019', '0x000008c2', '0x00000052', '0x0000002b',
       '0x00000029', '0x00000001'], dtype=object)

In [ ]:
df['tcp.analysis.initial_rtt'].astype(float).unique()

array([        nan, 1.30000e-04, 9.80000e-05, ..., 1.55505e-01,
       1.55916e-01, 1.53953e-01])

In [ ]:
#df['tcp.time_delta'].unique() 
df['tcp.time_relative'].unique()

array([0.00000000e+00,            nan, 2.49200000e-02, ...,
       4.85127391e+02, 4.85150747e+02, 4.85164078e+02])

In [ ]:
df['tcp.window_size_value'].unique() 

array([1024.,   nan,  422., ..., 5166.,  725.,  770.])

In [ ]:
df['tcp.hdr_len'].unique()

array([20., nan, 32., 40., 44., 24., 36., 28.])

In [ ]:
len(df['tcp.srcport'].unique())

65537

####HTTP related

In [ ]:
df[~df['http.content_length'].isna()].groupby(["category", "subcategory"]).count()

frame.time_epoch  frame.len  ...  trans.length  trans.stream
category subcategory                               ...                            
DDoS     DDoS_HTTP               38261      38261  ...         38261         38261
DoS      DoS_HTTP                57057      57057  ...         57057         57057
Normal   Normal                      1          1  ...             1             1
Scan     OS                       1467       1467  ...          1467          1467
         Service                 18510      18510  ...         18510         18510

[5 rows x 27 columns]

In [ ]:
df['http.response.code'].unique() # Categorical

array([ nan, 404., 200., 505., 405., 501., 302., 400., 301., 403., 408.,
       401.])

In [ ]:
len(df[~df["http.request.method"].isna()]["http.request.method"].unique())

92

In [ ]:
df["http.request.method"].unique()

array([None, 'POST', 'GET', 'OPTIONS', 'PROPFIND', 'HEAD', 'TRACE',
       'HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD',
       'HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD',
       'HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD',
       'HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,GET,GET,GET,GET,GET,GET,GET,GET,GET,GET,GET,GET,GET,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD',
       'HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,GET,GET',
       'GET,GET,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,H

In [ ]:
# Categorical 
df.groupby(["category", "subcategory"])["http.request.method"].value_counts().unstack(fill_value=0).add_prefix('flag').reset_index().rename_axis(None, axis=1)

category subcategory  flagGET  ...  flagPOST  flagPROPFIND  flagTRACE
0     DDoS   DDoS_HTTP        0  ...     19178             0          0
1      DoS    DoS_HTTP        0  ...     28566             0          0
2   Normal      Normal        1  ...         0             0          0
3     Scan          OS     1731  ...       240             0          0
4     Scan     Service      884  ...       266            43          9

[5 rows x 94 columns]

In [ ]:
df.groupby(["http.request.method"])["category"].value_counts().unstack(fill_value=0).add_prefix('flag').reset_index().rename_axis(None, axis=1)

http.request.method  ...  flagScan
0                                                 GET  ...      2615
1                                             GET,GET  ...         2
2                                         GET,GET,GET  ...         1
3                                     GET,GET,GET,GET  ...        59
4                                 GET,GET,GET,GET,GET  ...         1
..                                                ...  ...       ...
87  HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,HEAD,H...  ...        12
88                                            OPTIONS  ...       671
89                                               POST  ...       506
90                                           PROPFIND  ...        43
91                                              TRACE  ...         9

[92 rows x 5 columns]

In [ ]:
df["http.content_length"].unique()

array([        nan, 0.00000e+00, 2.77000e+02, 8.91000e+02, 9.42000e+02,
       4.41000e+02, 2.80000e+02, 3.01000e+02, 9.41000e+02, 2.82000e+02,
       1.05400e+03, 2.85000e+02, 3.06000e+02, 9.58000e+02, 1.02100e+03,
       2.87000e+02, 9.64000e+02, 1.10960e+04, 3.05000e+02, 1.15100e+04,
       8.00000e+00, 2.71000e+02, 1.40000e+02, 1.53000e+02, 1.44000e+02,
       1.49000e+02, 1.52000e+02, 1.58000e+02, 1.54000e+02, 1.63000e+02,
       1.48000e+02, 8.80000e+01, 2.88700e+03, 7.74000e+02, 3.21000e+02,
       2.86000e+02, 5.20000e+01, 3.09000e+02, 2.99000e+02, 2.93000e+02,
       2.89000e+02, 3.00000e+02, 2.90000e+02, 3.17000e+02, 3.08000e+02,
       3.50000e+01, 2.97000e+02, 2.94000e+02, 2.88000e+02, 2.84000e+02,
       2.81000e+02, 9.04100e+03, 2.79000e+02, 2.72000e+02, 3.40000e+01,
       3.57000e+02, 2.91000e+02, 2.83000e+02, 3.03000e+02, 1.40000e+01,
       3.07000e+02, 3.02000e+02, 3.16000e+02, 2.40000e+01, 3.47000e+02,
       1.05000e+02, 3.15000e+02, 5.19000e+02, 3.12000e+02, 2.950

In [ ]:
df["http.content_length_header"].equals(df["http.content_length"])

True

####Category

In [ ]:
df["category"].unique()

array(['Normal', 'DDoS', 'DoS', 'Scan', 'Theft'], dtype=object)

In [ ]:
df["subcategory"].unique()

array(['Normal', 'DDoS_HTTP', 'DoS_HTTP', 'OS', 'Service', 'DDoS_TCP',
       'DoS_TCP', 'DDoS_UDP', 'DoS_UDP', 'Data_Exfiltration',
       'Keylogging'], dtype=object)

##Process

In [ ]:
# Combine TCP and UDP columns: srcport, dstport, length and stream
df['srcport'] = np.where(pd.isnull(df['tcp.srcport']),df['udp.srcport'],df['tcp.srcport'])
df['dstport'] = np.where(pd.isnull(df['tcp.dstport']),df['udp.dstport'],df['tcp.dstport'])
df['trans.length'] = np.where(pd.isnull(df['tcp.len']),df['udp.length'],df['tcp.len'])
df['trans.stream'] = np.where(pd.isnull(df['tcp.stream']),df['udp.stream'],df['tcp.stream'])
df = df.drop(['tcp.srcport', 'udp.srcport', 'tcp.dstport', 'udp.dstport', 'tcp.len', 'udp.length', 'tcp.stream', 'udp.stream'], axis=1)

In [ ]:
# Unify values for categorical columns
# Convert values to float
df["ip.proto"] = df["ip.proto"].replace({'1,50': 3, '1,17': 4}).astype(float)
df['ip.flags.df'] = df['ip.flags.df'].replace({'0,0': 2, '0,1': 3}).astype(float)

In [ ]:
# Unify label column
df['subcategory'] = df['subcategory'].replace({'TCP': 'DDoS_TCP'})

In [ ]:
# Drop irrelevant columns
# Split embedded values in IP related columns (some ICMP packets contain the UDP packet inside the ICMP payload) 
dfp = pd.concat([df['frame.time_epoch'], df['frame.len'], df['ip.proto'], df['srcport'], df['dstport'], df['trans.stream'], df['trans.length'], 
                 df['tcp.analysis.initial_rtt'].astype(float), df['tcp.time_delta'], df['tcp.time_relative'], 
                 df['tcp.flags'], df['tcp.window_size_value'], df['tcp.hdr_len'], 
                 df['http.response.code'], df["http.request.method"], df["http.content_length"],
                 df['ip.ttl'].str.split(',', expand=True).rename({0: 'ip.ttl_1', 1: 'ip.ttl_2'}, axis=1), 
                 df['ip.hdr_len'].str.split(',', expand=True).rename({0: 'ip.hdr_len_1', 1: 'ip.hdr_len_2'}, axis=1),
                 df['ip.len'].str.split(',', expand=True).rename({0: 'ip.len_1', 1: 'ip.len_2'}, axis=1), 
                 df['ip.id'].str.split(',', expand=True).rename({0: 'ip.id_1', 1: 'ip.id_2'}, axis=1),
                 df['ip.flags.df'], df['attack'], df['category'], df['subcategory']], axis=1)

In [ ]:
# Fill nan values with max + 1.0
dfp['trans.stream'] = dfp['trans.stream'].fillna(dfp['trans.stream'].max() + 1.0)
dfp['trans.length'] = dfp['trans.length'].fillna(dfp['trans.length'].max() + 1.0)
dfp['tcp.time_delta'] = dfp['tcp.time_delta'].fillna(dfp['tcp.time_delta'].max() + 1.0)
dfp['tcp.time_relative'] = dfp['tcp.time_relative'].fillna(dfp['tcp.time_relative'].max() + 1.0)
dfp['tcp.window_size_value'] = dfp['tcp.window_size_value'].fillna(dfp['tcp.window_size_value'].max() + 1.0)
dfp["http.content_length"] = dfp["http.content_length"].fillna(dfp["http.content_length"].max() + 1.0)

In [ ]:
# Fill none values with '0x000fffff' (max is '0x0000ffff')
# Convert to int
dfp['ip.id_1'] = dfp['ip.id_1'].fillna('0x00010000').apply(lambda x: int(x, 16))
dfp['ip.id_2'] = dfp['ip.id_2'].fillna('0x00010000').apply(lambda x: int(x, 16))

In [ ]:
# Fill none values with '0x000008c3' (max is '0x000008c2')
dfp['tcp.flags'] = dfp['tcp.flags'].fillna('0x000008c3').apply(lambda x: int(x, 16))

In [ ]:
# Convert to float and fill nan values with 0.0
dfp['ip.ttl_1'] = dfp['ip.ttl_2'].astype(float).fillna(0.0)
dfp['ip.ttl_2'] = dfp['ip.ttl_2'].astype(float).fillna(0.0)
dfp['ip.hdr_len_1'] = dfp['ip.hdr_len_1'].astype(float).fillna(0.0)
dfp['ip.hdr_len_2'] = dfp['ip.hdr_len_2'].astype(float).fillna(0.0)
dfp['ip.len_1'] = dfp['ip.len_1'].astype(float).fillna(0.0)
dfp['ip.len_2'] = dfp['ip.len_2'].astype(float).fillna(0.0)

In [ ]:
# Fill none values with special values
dfp['ip.flags.df'] = dfp['ip.flags.df'].fillna(4.)
dfp['srcport'] = dfp['srcport'].fillna(65536.)
dfp['dstport'] = dfp['dstport'].fillna(65536.)

dfp['http.request.method'] = dfp['http.request.method'].fillna('NO')

In [ ]:
# Fill nan with 0. for tcp.analysis.initial_rtt, tcp.hdr_len, http.response.code
dfp = dfp.fillna(0.)

In [ ]:
dfp.to_csv('drive/My Drive/dataset/dataset_2_percent_processed.csv', index=False)

In [ ]:
dfp.dtypes

frame.time_epoch            float64
frame.len                     int32
ip.proto                    float64
srcport                     float64
dstport                     float64
trans.stream                float64
trans.length                float64
tcp.analysis.initial_rtt    float64
tcp.time_delta              float64
tcp.time_relative           float64
tcp.flags                     int64
tcp.window_size_value       float64
tcp.hdr_len                 float64
http.response.code          float64
http.request.method          object
http.content_length         float64
ip.ttl_1                    float64
ip.ttl_2                    float64
ip.hdr_len_1                float64
ip.hdr_len_2                float64
ip.len_1                    float64
ip.len_2                    float64
ip.id_1                       int64
ip.id_2                       int64
ip.flags.df                 float64
attack                        int32
category                     object
subcategory                 

In [ ]:
dfp.count()

frame.time_epoch            11252406
frame.len                   11252406
ip.proto                    11252406
srcport                     11252406
dstport                     11252406
trans.stream                11252406
trans.length                11252406
tcp.analysis.initial_rtt    11252406
tcp.time_delta              11252406
tcp.time_relative           11252406
tcp.flags                   11252406
tcp.window_size_value       11252406
tcp.hdr_len                 11252406
http.response.code          11252406
http.request.method         11252406
http.content_length         11252406
ip.ttl_1                    11252406
ip.ttl_2                    11252406
ip.hdr_len_1                11252406
ip.hdr_len_2                11252406
ip.len_1                    11252406
ip.len_2                    11252406
ip.id_1                     11252406
ip.id_2                     11252406
ip.flags.df                 11252406
attack                      11252406
category                    11252406
s